### ISSUE TITLE
Show/ hide icon displayed on sign in pages not working properly

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#10063]
### What is the expected behaviour?
If user clicks on show icon, it should display the actual password value entered by user.
If user clicks on hide icon, it should hide the password value and should appear as ***.

### What is the current behaviour?
The current behaviour is exact opposite of expected one. It hides the actual value on click of show.

### How to reproduce the issue?

1. Go to workspace sign in page
2. Enter password
3. Click on show/ hide icon

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/8b84580e-6e79-443e-94b3-089c11d37e6a

**Comment by MK884** [comment]
the same problem exists in signup page also
the problem is only with the placement of the `EyeShow` and `EyeHide` components in `frontend/src/LoginPage/LoginPage.jsx` and `frontend/src/SignupPage/SignupPage.jsx`

# solution

correctly rendering `EyeShow` and `EyeHide` components with respect to `this.state?.showPassword` 

This issue is present on both the login and signup pages. I have identified the necessary changes and am ready to submit a PR to resolve this issue.
