### ISSUE TITLE
Brand colors for 'add datasource button'

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#1617]
### What is the expected behaviour?

Add datasource button should have brand colors
### What is the current behaviour?

It does not have brand colors

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/20333972/146947623-7b3bae03-e646-42c8-97d5-dd70588472de.png)

**Comment by marboleda** [comment]
@sherfin94 May I work on this? I have the app up and running on my Ubuntu server.

Also, I am not entirely sure what this issue is requesting. This is what I see on my local instance:
![image](https://user-images.githubusercontent.com/30060106/149814273-a54f87a1-f888-4854-ba78-5f2a8bd3e2fa.png)

Is this issue requesting that it be modified to look like the screenshot provided?

**Comment by sherfin94** [comment]
Hey @marboleda , sorry for the delayed response.

Looks like this issue got automatically resolved by another design update. I'll have to close this issue.
Feel free to explore other issues or raise one if you feel something could be improved.

Thank you for your enthusiasm!
