### ISSUE TITLE
Default value is not displayed on Textarea widget.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#2454]
### What is the expected behaviour?
The default value should be displayed on the textarea widget

### What is the current behaviour?
Default value is not being displayed on the textarea widget.

### How to reproduce the issue?

1. Drag and drop textarea on canvas.
2. Observe the canvas.

### Screenshots or Screencast
https://drive.google.com/file/d/1Ml_gVheYCt_jbzMpMYBQsp6iBiJLo5QV/view?usp=sharing

**Comment by KaviiSuri** [comment]
Can I work on this issue?

**Comment by KaviiSuri** [comment]
I'm new to the codebase but it seems like there are 2 possible reasons for this:
1. using `exposedVariables.value` instead of `properties.value` in [frontend/src/Editor/Components/TextArea.jsx](https://github.com/ToolJet/ToolJet/blob/c836d861cf7a5e712aaf92ba9040f2569690e3b6/frontend/src/Editor/Components/TextArea.jsx)
2. In [frontend/src/Editor/Components/components.js](https://github.com/ToolJet/ToolJet/blob/72ca2f5868e806062f4a9eb68fb89f7b00c0f34a/frontend/src/Editor/Components/components.js) `exposedVariables.value` is `{}`

Can someone give me some clarity on this?

Please assign me the issue if it's available.

**Comment by Navaneeth-pk** [comment]
@KaviiSuri assigning the issue to you.
@arpitnath will be the right person to help with the question in comment above.

**Comment by arpitnath** [comment]
Hi @KaviiSuri,
Yes changing the exposed variable's value to an empty string will fix the issue.

```js
      value: { }, 
```
to `value: ""` in `frontend/src/Editor/Components/components.js --> line 669`

**Comment by KaviiSuri** [comment]
Thanks, I'll post a PR!
