### ISSUE TITLE
Unable to preview rest api request in query editor

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#2740]
### Environment
MacOS

### What is the expected behaviour?
Should be able to preview the response from server

### What is the current behaviour?
Unable to preview the response from server

### How to reproduce the issue?

1. Use this hosted link to get a static response for testing: https://reqres.in/api/users?page=2
2. Observe the error message
3. It says statusCode is undefined

### Screenshots or Screencast
<img width="777" alt="image" src="https://user-images.githubusercontent.com/12490590/161537984-8eea2f22-fb3f-41bd-9c13-bd5ebaac5c25.png">

**Comment by mslourens** [comment]
The problem is that you are missing the api URL part of the url, which is displayed in a greyed out disabled input:
<img width="986" alt="image" src="https://user-images.githubusercontent.com/1907152/163365946-71525645-bfea-4726-af09-6d8662e4072e.png">
When you enter the part of the path in the input for preview, the preview return with data. 
There is an issue with this disabled input, because after clicking around this input disappears and only the path input remains. If you enter the whole url in that input, it will throw an error as you described.
