### ISSUE TITLE
Remove "new tab"/"target blank" icon from the menu bar

### ISSUE THREAD

**Issue by shivangT** [ToolJet/ToolJet#3121]
### What is the expected behaviour?
Remove these icons and make the texts(menu items) look like a link.

### What is the current behaviour?
Clicking on these icons redirects to the respective link in a new tab  

### How to reproduce the issue?

1. Visit https://docs.tooljet.com/docs/
2. On the top right corner you will find the menu items (Refer to the screenshot below)

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/32157641/170248357-892e3db7-7ac3-4cb9-bb2e-dd9305fc861a.png)

### Any possible solutions?
Assign the brand color to the texts(menu items).
You are free to design your own UI.

**Comment by Anjacodes** [comment]
Hi @shivangT, can I take this issue?

**Comment by shivangT** [comment]
Hello Anja,

Sure you can go ahead and pick this issue. Let me know if you have any
questions or need help with anything.

Have a good time coding on ToolJet.

**Comment by Anjacodes** [comment]
Hey @shivangT, I've tried setting up Tooljet on my local machine but when running it on localhost, I'm getting an error and nothing is rendered. The error is apparently in the fetch request in the app.service.js file. Any ideas on what I might be missing? Also, it might be appropriate to tell you at this point that this is my first contribution to an OS project and since I don't know how long it will take me to solve this, I won't  take it personally if you prefer assigning someone else 😅 .
Thank you for your help or for pointing me to the right place to ask my question!

<img width="871" alt="Screen Shot 2022-05-26 at 15 17 09" src="https://user-images.githubusercontent.com/75140420/170573039-b52da168-f755-431c-a2c1-a6ab5f561fbe.png">

**Comment by Anjacodes** [comment]
Hi @shivangT, I created [this PR](https://github.com/ToolJet/ToolJet/pull/3138) to resolve the issue.

**Comment by shivangT** [comment]
Hello @Anjacodes,

If you face any hurdles while working on ToolJet issues kindly reach out to
us on our slack channel. We will try to respond at the earliest. Apologies
for not responding on time.

Amazing! 😀
Congratulations on your first contribution.  We will review the PR and get
back to you soon.

Would you like to work on other good first issues by that time?
https://github.com/ToolJet/ToolJet/issues/3085

Thanks and Regards

**Comment by Anjacodes** [comment]
Hi @shivangT, thank you for your message and for being so welcoming to newbies like myself, I greatly appreciate it 🙏 ! I'll definitely check out your other issues next week. I loved the new challenge! Thank you again and have a lovely weekend!

**Comment by shivangT** [comment]
Hey @Anjacodes,

Sure, let me know if you need help with picking new issues, can guide you
over to select UI related good first issues so that you enjoy your new
challenges. We keep updating our issues log every day, so you are free to
opt in anytime✌🏼

We’re a community driven company and we really appreciate your effort to
help us grow. Its is a journey which is not possible without small and big
contributions from our community members.

Have a great week ahead. Thank you for your time coding for ToolJet. Talk
to you soon!! 😊
