### ISSUE TITLE
[localization] Translate strings in Indonesian

### ISSUE THREAD

**Issue by depapp** [ToolJet/ToolJet#4286]
### Is your proposal related to a problem?

Add translations in Indonesian.

### Describe the solution you'd like

The strings needs to be translated:
```json
    "globals":{
    },
    "errorBoundary":,
    "viewer":,
    "app":{
    },
    "stripe":,
    "openApi":{
    },
    "slack":{
    },
    "googleSheets":{
    },
    "profile": {
    },
    "loginSignupPage":{
    },
```

hi @withshubh please assign to me & I'll work on it!

**Comment by depapp** [comment]
created the PR #4287

**Comment by withshubh** [comment]
Hi @depapp 👋  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you but please don't create the PRs unless the issue is assigned.

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by depapp** [comment]
hi @withshubh 
noted with thanks 🙇🏻
