### ISSUE TITLE
PGPASSWORD environment variable written into log

### ISSUE THREAD

**Issue by aryounce** [ToolJet/ToolJet#4795]
### Version Information
`1.29.0`

### Environment
Everywhere except(?) ToolJet Cloud.

### What is the expected behaviour?
Passwords are not written into logs.

### What is the current behaviour?
When database creation fails the entire command string including the value of the `PGPASSWORD` environment variable is written into the console log. We discovered this in CloudWatch Logs when attempting to start ToolJet in an ECS cluster.

### How to reproduce the issue?

1. Start the ToolJet container with incorrect Postgres permissions or partially incorrect database connection configuration.
2. Observe log output.

### Please provide any traces or logs that could help here.
```
Error: Command failed: PGPASSWORD=<redacted> createdb -h <redacted>.us-east-1.rds.amazonaws.com -p 5432 -U tooljet tooljet
```

### Any possible solutions?
Change log emission to use a format string that only includes specific information relevant to the error.

### Can you identify the location in the driver source code where the problem exists?
- [Command string creation](https://github.com/ToolJet/ToolJet/blob/883a55a88cac54290e8f68b40872e76b5c10aee4/server/scripts/create-database.ts#L43)
- [Probable error log that includes full command string](https://github.com/ToolJet/ToolJet/blob/883a55a88cac54290e8f68b40872e76b5c10aee4/server/scripts/create-database.ts#L61)

### If the bug is confirmed, would you be willing to submit a PR?
We can't at this time, but are in the process of evaluating ToolJet for possible internal use.

**Comment by withshubh** [comment]
Hey @aryounce - Thanks for creating the issue. We'll fix this soon and let you know.

**Comment by andreyazbarov** [comment]
guys, the issue still persists in otherway:

On a fresh install via docker-compose script (as described in manual https://docs.tooljet.com/docs/setup/docker, "With in-built PostgreSQL" and https://docs.tooljet.com/docs/setup/env-vars): 
1. PG_PASS variable in .env changed from "postgres" to "any pass".
2. ToolJet can't start due to unable to authenticate with "any pass"
3. Logs show the error with "any pass"
4. As appeared Postgres installed with default password "postgres" instead of of "any pass"

If Postgre password change manually (with Navicat for example) and then fill to .env and docker-compose down and up back - the password using correctly, so it seams the issue appears during first "docker-compose up -d".

P.S. previously I bypassed the bug and forgot to changed the default password manually - my DB was hacked and stolen by someone (I don't want to blame anyone, it's just my mistake).

But, I'm not sure that my issue is fully relevant to current.

Best regards,
Andrey
