### ISSUE TITLE
Updated page name is not reflecting the Preview URL

### ISSUE THREAD

**Issue by dishag18** [ToolJet/ToolJet#6501]
### What is the expected behaviour?
The preview URL should reflect the exact page name provided by user, 
-should not be any case differences (test vs TEST)
-should reflect the updated page names in URL, across all the pages. If user rename home page or any other page, the updated page name should be reflected in the preview URL
-When user provides any custom sharable link and accesses it, for the first time '/home' string is missing from URL. It appears when user switches in between the pages
-Navigate from any page to the preview screen, verify preview and come back to delete the same page. After deletion of page, go to preview screen again, verify the URL, it still shows the deleted page name in the URL

### What is the current behaviour?
Inconsistency in page name and Preview URL is observed.

### How to reproduce the issue?

1. create multipage app
2. rename any page and click on preview
3. verify the Preview URL

### Screenshots or Screencast

https://github.com/ToolJet/ToolJet/assets/125240229/0a8194fc-b204-4bbd-bb01-53af75f7b089

https://github.com/ToolJet/ToolJet/assets/125240229/39484cd0-3ea9-4fc7-86d3-747d7887faa0

**Comment by johnsoncherian** [comment]
This is the expected behaviour since page name and the url can be different. To change the url the user can update the page handle (refer image below).
<img width="613" alt="image" src="https://github.com/ToolJet/ToolJet/assets/57667706/71bf7184-c55d-4571-bd7a-66a9eb302201">

However there was bug which caused a new url to reflect in preview app only if the page is refreshed. This is fixed under this
issue
FYI: @kavinvenkatachalam @shubh22
