### ISSUE TITLE
Refactor: Updation of the text Datasource 101 on the Datasource Page

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7028]
**Description:**

The text on the datasources tab when no datasources are added shows the text as **“Datasources 101”**. This text needs to be updated to just “Datasource”

**Steps to Reproduce:**

1. Open ToolJet on your browser.
2. Create a fresh workspace by clicking on bottom of the sidebar where it says **“ToolJet”** with an arrow on its side. 
3. Look for the datasources tab in the left side bar of icons.
4. Open the datasources tab and check for the text in the middle of the screen

**Expected Output:**

The text on the datasource page which is seen as **“Datasources 101”** should be updated with the text **“Datasources”.**

<img width="1437" alt="Screenshot 2023-07-14 at 1 07 04 PM" src="https://github.com/ToolJet/ToolJet/assets/85864291/9f0d7f00-8ae1-4f6e-b7a0-1810e63d4a48">

**Comment by Dvinod1** [comment]
@ShazanRizvi  I have solved the issue, can I make PR ?

**Comment by tejakummarikuntla** [comment]
Hello @Dvinod1,

I sincerely appreciate your contribution, and I would like to kindly request you to review the [contributor guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md) and ensure that you raise pull requests (PRs) for the issues assigned specifically to you. Regrettably, since the issue in question has not been assigned to you, we will have to close this PR. However, I encourage you to explore up for grabs without good first issue tag, that may be available for you to work on. Thank you for your understanding, and I look forward to your continued involvement in the project.

**Comment by Dvinod1** [comment]
sorry for the problem I caused. 
I will keep thins in mind, Thank you.

**Comment by mustajab-ikram** [comment]
Hi @tejakummarikuntla ! I would like to work on issue #7028, which involves updating the text "Datasources 101" to "Datasources" on the Datasource Page. Could you please assign this issue to me? 
I am eager to contribute to the project. 
Thank you!

**Comment by tejakummarikuntla** [comment]
Hey @mustajab-ikram , thanks for your interest. Assigned this to you.
