### ISSUE TITLE
[Docs]: Broken documentation links in the plugins folder in repository.

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7097]
**Description:**

When navigating to the ToolJet repository on GitHub and accessing the plugins folder, clicking on certain documentation links results in a "Page Not Found" error message. Despite the existence of documentation for the plugins, the links appear to be broken and do not lead to the correct pages. This issue is hindering users from accessing the relevant documentation for the plugins, causing confusion and frustration.

**Steps to Reproduce:**

1. Open the ToolJet repository on GitHub.
2. Find and click on the plugins folder and open it.
3. Scroll to the end of the page and click on the documentation link in the Readme section.
4. Observe the page which opens up when the link is clicked.

**Expected Output:**

The link present in the Readme file of the plugin folder should take the user to the [documentation](https://docs.tooljet.com/docs/contributing-guide/marketplace/creating-a-plugin) of the plugins.
<img width="1437" alt="PageNotFound" src="https://github.com/ToolJet/ToolJet/assets/85864291/34d5d01d-933f-484e-a508-86a9e4dd59f1">
<img width="1440" alt="PluginFoder" src="https://github.com/ToolJet/ToolJet/assets/85864291/14c9e945-735f-421a-a495-217dcb431a0c">

**Comment by Saurabhmahto** [comment]
please assign me the issue.

**Comment by tejakummarikuntla** [comment]
Hello @Saurabhmahto, we kindly request that you follow the [contributor guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md), which include commenting about your interest before starting work on any issues. It's important for issues to be assigned before any work begins.

Since there are no other requests for the issue, and you are a first-time contributor as well, we warmly welcome you to the project and hereby assign this issue to you.

**Comment by JunedKhan101** [comment]
@tejakummarikuntla Can I pick this up?

**Comment by Saurabhmahto** [comment]
I'll again need to create a PR?

**Comment by Lovepreet013** [comment]
@tejakummarikuntla I would like to take this issue
