### ISSUE TITLE
Enabling / disabling table pagination buttons is not reloading with data

### ISSUE THREAD

**Issue by MarcelGeo** [ToolJet/ToolJet#7982]
### Version Information

2.19.1

### Environment
    Docker

### What is the expected behavior?
Pagination is working and properly enabling / disabling buttons. I followed this tutorial and fx enabling / disabling pagination buttons.

https://docs.tooljet.com/docs/how-to/use-server-side-pagination/

### What is the current behavior?
- Pagination in table is not enabling  **previous button**.
- Page number is not updating from 1 to 2 after click on next button.

### How to reproduce the issue?

1. Make fx to enable / disable previous button in server side pagination

### Screenshots or Screencast
![image](https://github.com/ToolJet/ToolJet/assets/12643115/fbbed307-6d28-4239-9ed4-8164d5173ee0)

**Comment by manishkushare** [comment]
Hey @MarcelGeo, We fixed` Page number is not updating from 1 to 2 after clicking on next button.` in one of the recent releases, for your reference, we are attaching the reference of the [PR](https://github.com/ToolJet/ToolJet/pull/7827).

Regarding, ` Pagination in the table is not enabling the previous button.` We cannot reproduce this issue, and it seems to work fine. It would be great if you can provide us with steps to reproduce it so that we can verify it.

**Comment by MarcelGeo** [comment]
@manishkushare I will update to a newer version with table fixes to test if any issues are occurring.

**Comment by MarcelGeo** [comment]
After update. Pagination is correct. You can close this issue.
