### ISSUE TITLE
Adding a section for commonly used data sources

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#8836]
**Current scenario/Problem statement**- Data sources are categorized based on type and sorted alphabetically for ease of use. However, with the variety of data sources available, the most commonly used data sources like RestAPI, Postgres, MongoDB, etc get pushed to the bottom of the list- which requires the user to scan through the whole list. (Ref screenshot)

**Solution**- Adding a commonly used section, similar to the one while creating queries, will help reduce decision-making time for the user and enhance experience in a small yet important aspect. 

![image](https://github.com/ToolJet/ToolJet/assets/127945292/16621a29-d75d-405a-9cb3-9ae01faec0cf)

**Comment by sid0-0** [comment]
Are you suggesting adding a new category called 'Commonly Used' which will contain exclusive options or duplicate options? For example, Redis is commonly used, it could be in both Commonly Used and Databases category, which seem logical, instead of exclusive options.

Another option is having a 'Commonly Used' subcategory within each category and list commonly used options in that category as a part of that sub category.

**Comment by nechalmaggon** [comment]
@sid0-0 Hello, the suggestion here is to add a new category called `Commonly used` which will contain duplicate options. This way the users will see the common few as the first thing on the page but can still find the data source and others based on the categories so there's no confusion or change in existing functionality and sorting. Hope that answers your question!
