### ISSUE TITLE
Notification modal to be resized

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#9183]
Notification modal should be resized so as to not have horizontal scroll in the container

<img width="364" alt="Screenshot 2024-03-25 at 12 29 17 PM" src="https://github.com/ToolJet/ToolJet/assets/127945292/3e720951-5143-4fe3-b394-f472eba589a9">

**Comment by irfan-iiitr** [comment]
can i work on this?

**Comment by irfan-iiitr** [comment]
what are the steps to reproduce the error?

**Comment by karan-rathod-316** [comment]
Hi @irfan-iiitr,

Assigning this issue to you. Happy coding :-)

**Comment by karan-rathod-316** [comment]
@irfan-iiitr 

**Steps to replicate the issue:**
1. Login to ToolJet
2. Click on the Notifications icon in the left side bar
3. A modal will appear with a scroll bar
![Recording 2024-04-01 at 15 39 05](https://github.com/ToolJet/ToolJet/assets/58169101/0ff6eb64-ef17-4cd9-88a0-7ef7fe3a7630)

**Expected behavior:**
The Notification modal should not have horizontal scroll, it should be wide enough to display the notification content without the need to scroll horizontally.

**Comment by karan-rathod-316** [comment]
Hi @irfan-iiitr,

Any updates on this?

**Comment by irfan-iiitr** [comment]
I am currently busy with my exams . I am sorry I totally forgot about this. Please assign this task to someone else.

**Comment by Sadaf-A** [comment]
@karan-rathod-316 I'd like to work on this could you please assign

**Comment by karan-rathod-316** [comment]
Thank you for raising the PR @Sadaf-A, moving this to review.
