### ISSUE TITLE
Tooljet database CTAs cutoff on mobile

### ISSUE THREAD

**Issue by david-everett** [ToolJet/ToolJet#9383]
### What is the expected behaviour?
CTAs should have images underneath them which creates the space for the full CTA to load.

### What is the current behaviour?
Not all items are having their images load beneath them on mobile. This is causing the CTAs to be cutoff.

### How to reproduce the issue?
1. Go to [Tooljet Database](https://www.tooljet.com/database) page on mobile
2. Scroll down to "bring your data"
_Note: It looks fine when testing mobile devices from a desktop_

### Screenshots or Screencast
![CTAs Cutoff](https://github.com/ToolJet/ToolJet/assets/98620729/2527e589-9c8b-473e-a5fa-4d3fc471e8e2)

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by AnkityadavIITR** [comment]
@david-everett hii david i tried to look into this issue but , in my phone it's working fine i'm attaching the photos
![WhatsApp Image 2024-04-16 at 21 15 14](https://github.com/ToolJet/ToolJet/assets/89698311/456597ce-f72e-4835-b68d-9e09d93c12be)
![WhatsApp Image 2024-04-16 at 21 15 15](https://github.com/ToolJet/ToolJet/assets/89698311/0da6470f-0aed-4dbe-b196-3ba7f0aaa93e)
if the issue is specific to some mobile viewport only. please let me know I would like to work on it

**Comment by shubh22** [comment]
This repo doesn't track bugs in tooljet.com website.
