### ISSUE TITLE
Add base URL setting for better reverse proxy support

### ISSUE THREAD

**Issue by igoro00** [ToolJet/ToolJet#983]
### Is your proposal related to a problem?

My production server has been given a subdomain but not *.subdomain. I can't control that, so my reverse proxy forwards requests to various apps based on subdirectory. Tooljet doesn't have base url setting so I can't use it in prod properly.  

### Describe the solution you'd like

Add a base URL setting. For example that's how sonarr(a popular self-hosted PVR for series and tv shows) does it:
![image](https://user-images.githubusercontent.com/35789870/136823921-737e7b7f-c096-4db5-bd7b-b86a102ade3d.png)

**Comment by exetico** [comment]
Hi @akshaysasidrn 

In the [deployment guide](https://docs.tooljet.com/docs/deployment/docker) we're told to use `TOOLJET_HOST ` to define the URL - and I expected that to handle the subpath too, like `https://mydomain.com/tooljet`, but it doesn't work on my end.

@igoro00  - How did you end up fixing this? I'm facing the same problem with the resources like `main.js`. The reverse-proxy works, but I'm unable to add the subpath to the requests. To the client tried to fetch data from `/` instead of `/tooljet`.

**Comment by igoro00** [comment]
> Hi @akshaysasidrn 
> 
> In the [deployment guide](https://docs.tooljet.com/docs/deployment/docker) we're told to use `TOOLJET_HOST ` to define the URL - and I expected that to handle the subpath too, like `https://mydomain.com/tooljet`, but it doesn't work on my end.
> 
> @igoro00  - How did you end up fixing this? I'm facing the same problem with the resources like `main.js`. The reverse-proxy works, but I'm unable to add the subpath to the requests. To the client tried to fetch data from `/` instead of `/tooljet`.

I requested network admin to set up * subdomains for my server and proxied tooljet to its own subdomain using nginx proxy manager.

I'm building a real dashboard with react and ditched tooljet because tooljet is(was) too alpha to use in production. It was hard to get a simple table from graphql query, and run mutations when user changes data or clicks on actions. In fact harder than building the whole thing with react and urql. Bugs everywhere(i would have to become a full-time contributor instead of actually doing my job to get it eventually working in production), terrible built-in code(SQL and JS) editor and underwhelming UI. Wasn't worth it for now.

**Comment by exetico** [comment]
What a fast reply, thanks! Sadly I don't have the option for a sub-domain, so I'll keep fighting the issue. I must say a "subpath" option are **very much needed**.

**Comment by akshaysasidrn** [comment]
@exetico I had looked into this issue recently. The issue here is that on docker-compose env, the client image is already built. `ASSET_PATH` will only be considered when the client is being bundled and hence setting env vars for the client in dockerized env won't be picked up.

For now, you would have to make use of some proxying rules to redirect assets requested to the subpath where the assets are hosted or you would have to bundle the client with `ASSET_PATH` specified.

**Comment by exetico** [comment]
Hi @akshaysasidrn . I must have overlooked your reply or something.

As pr. my understanding I can't do that kind of proxying in Caddy. It as possible if the resource was required on a subpath, but should be found in the parent path. But here it's the other way around, and I cant have Caddy to rewrite every item requested, to look in the parent-path of a proxy-element.

I can't let ToolJet use my main domain (with no sub-path), and Caddy can't rewrite the entire route to try and fetch data from the tooljet docker container.

Normally users would make a proxy-rule like this in Caddy, if the subpath was handled by the technical solution.
```
        route /tooljet* {
                uri strip_prefix /tooljet
                reverse_proxy {
                        to 127.0.0.1:8089
                }
        }
```

![image](https://user-images.githubusercontent.com/3549445/159713846-c5d1b58a-16e4-47da-bd7c-28d278d832da.png)

![image](https://user-images.githubusercontent.com/3549445/159714087-823e2ffb-1a9e-4d20-94c4-9e4c8a330c49.png)

Could it be considered to get ASSET_PATH inthe run-time, instead of baked in the build-process? I've not found many solutions where it's not possible to change the proxy path in other ways than during the build.

It's a must have for people hosting multiple (VERY NICE!) open source tools, for all kinds of different use cases.

**Comment by akshaysasidrn** [comment]
@exetico You are right, the documentation needs to be better around `ASSET_PATH`. Need to check for some workaround for this. Probably using an image which gets bundled when the container is started makes sense.

**Comment by exetico** [comment]
Are there any progress related to this? It's odd that the application doesnt' support a reverse_proxy setup, without compiling the code. Look at Metabase and simular. None of these has that kind of requirement in their primary shipped container.

**Comment by Navaneeth-pk** [comment]
Reverse proxy support has been released in the latest version: https://github.com/ToolJet/ToolJet/releases/tag/v1.24.0. An additional step is required during setup, it is mentioned in the release notes. 

Please feel free to ping us here or on our Slack community if you face any issue: https://tooljet.com/slack. 

@igoro00 @exetico

**Comment by exetico** [comment]
Thank you for pushing this through! Here's my notes, for people finding this on Google or simular.

I've used port `8069` for the below example as the port where Caddy is hitting ToolJet.

The part in Caddy v2 now looks like this:
```
        route /tooljet* {
                reverse_proxy {
                        to 127.0.0.1:8069
                }
        }
```

My Docker-file looks like this - but **please** follow the ToolJet docs for the most updated example(s)!

```yaml
  tooljet:
    container_name: tooljet
    tty: true
    stdin_open: true
    image: tooljet/tooljet-ce:latest
    restart: always
    env_file: tooljet.env
    ports:
      - 8069:80
    depends_on:
      - tooljet_postgres
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    command: npm run start:prod

  tooljet_postgres:
    container_name: tooljet_postgres
    image: postgres:13
    restart: always
    volumes:
      - postgres:/data/postgres
    env_file: postgres.env

volumes:
  postgres:
```

The `logs`-directory could be added too, but that was not really important for current case.

_I know the client PORT is defined in environment->`PORT`, but I'd like to do it like this, to stick to the default config as much as possible, and just make a route from 80 to 8069._

I'll skip sharing the env-files, but here's the most relevant things in `tooljet.env`, where `myproxieddomainthroughcaddy.com` is my domain:
```
TOOLJET_HOST=https://myproxieddomainthroughcaddy.com/tooljet
TOOLJET_SERVER_URL=https://myproxieddomainthroughcaddy.com/tooljet
SUB_PATH=/tooljet/
```

Kindly note that you'll need to use `tooljet/tooljet-ce:latest`.

It's not possible to use the `tooljet-client-ce` and server separately, if you'd like to use the `SUB_PATH` parameter ([ref](https://tooljet.slack.com/archives/C01TY0ZGH6X/p1663325080923549?thread_ts=1663324935.837899&cid=C01TY0ZGH6X)).
